"use client";
import { useState, type FormEvent } from "react";
import { Mail, ArrowUpRight, MessageSquare, ShieldCheck, Phone } from "lucide-react";
import Link from "next/link";
import { useLanguage } from "./LanguageRuntime";

export default function LandingContact() {
  const { language } = useLanguage(); const en = language === "en";
  const [draft, setDraft] = useState<{ mailto: string; gmail: string } | null>(null);
  const input = "mt-2 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-3 py-3 text-sm text-slate-900 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100";
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const subject = String(data.get("subject") || "").trim().replace(/[\r\n]/g, " ");
    const body = [
      String(data.get("message") || "").trim(),
      "",
      `${en ? "Name" : "Nom"}: ${String(data.get("name") || "").trim()}`,
      `Email: ${String(data.get("email") || "").trim()}`,
    ].join("\r\n");
    const mailto = `mailto:juniormuteba10@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    const gmail = `https://mail.google.com/mail/?view=cm&fs=1&to=juniormuteba10%40gmail.com&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    setDraft({ mailto, gmail });
    const submitter = (event.nativeEvent as SubmitEvent).submitter;
    const useGmail = submitter instanceof HTMLButtonElement && submitter.value === "gmail";
    window.location.assign(useGmail ? gmail : mailto);
  }
  return <section id="contact" data-no-translate className="scroll-mt-24 border-t border-slate-200 bg-slate-50 px-6 py-16 sm:py-24"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_1.3fr]">
    <div className="lg:pr-8"><div className="mb-6 inline-flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100 text-blue-700"><MessageSquare size={24}/></div><span className="block text-xs font-semibold uppercase text-blue-700">{en ? "Here to help" : "À votre écoute"}</span><h2 className="mt-3 max-w-md text-3xl font-bold leading-tight text-slate-950">{en ? "Let's talk about your shop." : "Parlons de votre boutique."}</h2><p className="mt-5 max-w-sm text-sm leading-7 text-slate-600">{en ? "Getting started, a feature question or a suggestion: tell us what you need." : "Premiers pas, question sur une fonctionnalité ou suggestion : dites-nous ce dont vous avez besoin."}</p><div className="mt-8 divide-y divide-slate-200 border-y border-slate-200"><a href="mailto:juniormuteba10@gmail.com" className="group flex items-center gap-3 py-5 text-slate-800 hover:text-blue-700"><Mail size={20} className="shrink-0 text-blue-600"/><div className="min-w-0 flex-1"><span className="block text-xs text-slate-500">Email</span><span className="break-all text-sm font-semibold">juniormuteba10@gmail.com</span></div><ArrowUpRight size={16} className="shrink-0"/></a><a href="tel:+243990835638" className="flex items-center gap-3 py-5 text-slate-800 hover:text-blue-700"><Phone size={20} className="shrink-0 text-blue-600"/><div><span className="block text-xs text-slate-500">{en ? "Phone" : "Téléphone"}</span><span className="text-sm font-semibold">+243 990 835 638</span></div></a></div><div className="mt-6 flex items-start gap-3 text-xs leading-6 text-slate-500"><ShieldCheck size={18} className="mt-1 shrink-0 text-emerald-600"/><p>{en ? "Your details are used to respond to your request. Never share passwords or verification codes." : "Vos coordonnées servent à répondre à votre demande. Ne partagez jamais vos mots de passe ou codes de vérification."}</p></div><div className="mt-5 flex flex-wrap gap-5 text-xs font-semibold text-blue-700"><Link href="/confidentialite" className="underline underline-offset-4">{en ? "Privacy" : "Confidentialité"}</Link><Link href="/conditions" className="underline underline-offset-4">{en ? "Terms of use" : "Conditions d'utilisation"}</Link></div></div>
    <form onSubmit={submit} className="min-w-0 space-y-5 border-t border-slate-200 pt-8 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><div><h3 className="text-xl font-bold text-slate-900">{en ? "Send us a message" : "Écrivez-nous"}</h3><p className="mt-2 text-xs text-slate-500">{en ? "Required fields *. Your email app will open with a draft; you send it yourself." : "Champs obligatoires *. Votre messagerie ouvrira un brouillon ; vous confirmerez vous-même l’envoi."}</p></div>

      <fieldset className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-800">{en ? "Full name" : "Nom complet"} <span className="text-rose-600">*</span><input name="name" autoComplete="name" required minLength={2} maxLength={100} className={input}/></label><label className="text-sm font-medium text-slate-800">Email <span className="text-rose-600">*</span><input name="email" type="email" autoComplete="email" required maxLength={254} className={input}/></label></div><label className="block text-sm font-medium text-slate-800">{en ? "Subject" : "Objet"} <span className="text-rose-600">*</span><input name="subject" required minLength={3} maxLength={120} className={input}/></label><label className="block text-sm font-medium text-slate-800">Message <span className="text-rose-600">*</span><textarea name="message" required minLength={10} maxLength={4000} rows={5} className={`${input} resize-y`}/></label><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" className="hidden"/><label className="flex items-start gap-3 text-xs leading-6 text-slate-600"><input type="checkbox" name="consent" required className="mt-1.5 h-4 w-4 shrink-0 accent-blue-600"/><span>{en ? "I agree to the use of my details to respond to this message." : "J'accepte l'utilisation de mes coordonnées pour répondre à ce message."} <Link className="text-blue-700 underline" href="/confidentialite">{en ? "Privacy" : "Confidentialité"}</Link></span></label><button type="submit" className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-700 sm:w-auto"><Mail size={18}/> {en ? "Continue in my email app" : "Continuer dans ma messagerie"}</button><button type="submit" name="destination" value="gmail" className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-6 py-3 text-sm font-semibold text-slate-800 hover:bg-slate-100 sm:ml-3 sm:w-auto"><ArrowUpRight size={18}/>{en ? "Open Gmail" : "Ouvrir Gmail"}</button></fieldset>
      <p className="text-xs leading-6 text-slate-500">{en ? "Nothing opens? Choose Open Gmail, or configure an email app on your phone. You will still need to send the message from your mailbox." : "Rien ne s'ouvre ? Choisissez Ouvrir Gmail, ou configurez une application de messagerie sur votre téléphone. Vous devrez ensuite envoyer le message depuis votre messagerie."}</p>
      {draft && <div role="status" className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-900"><p>{en ? "Your draft is ready. No message has been sent by this site." : "Votre brouillon est prêt. Aucun message n'a été envoyé par ce site."}</p><div className="mt-3 flex flex-wrap gap-4"><a href={draft.mailto} className="font-semibold underline">{en ? "Open email app" : "Ouvrir ma messagerie"}</a><a href={draft.gmail} rel="noreferrer" className="font-semibold underline">{en ? "Continue in Gmail" : "Continuer dans Gmail"}</a></div></div>}
    </form></div></section>;
}
